# Generated by Django 5.1.4 on 2025-01-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_alter_task_user_rename_task_text_task_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
    ]
